name: BCE PTA
favicon: null
layout_spectrum: 0.44875795929692686
typography_spectrum: 0.08099944004788995
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.4390244141686708
  lightness: 0.38376536848954856
  saturation: 0.28734821057878435
  rhythmicContrast: 0.8143491249065846
purpose: []
